# Generated by Django 5.0.7 on 2024-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('current_designation', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
