# Generated by Django 5.0.7 on 2024-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_employee_image_alter_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to=' '),
        ),
    ]
