# Generated by Django 5.0.7 on 2024-08-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='news/'),
        ),
    ]
